/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ExploreCoastalKarnatakaRouteImport } from './routes/explore.coastal-karnataka'
import { Route as ExploreHeritageTrailsRouteImport } from './routes/explore.heritage-trails'
import { Route as ExploreHiddenVillagesRouteImport } from './routes/explore.hidden-villages'
import { Route as ExploreWesternGhatsRouteImport } from './routes/explore.western-ghats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const ExploreCoastalKarnatakaRoute = ExploreCoastalKarnatakaRouteImport.update({
  id: '/coastal-karnataka',
  path: '/coastal-karnataka',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreHeritageTrailsRoute = ExploreHeritageTrailsRouteImport.update({
  id: '/heritage-trails',
  path: '/heritage-trails',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreHiddenVillagesRoute = ExploreHiddenVillagesRouteImport.update({
  id: '/hidden-villages',
  path: '/hidden-villages',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreWesternGhatsRoute = ExploreWesternGhatsRouteImport.update({
  id: '/western-ghats',
  path: '/western-ghats',
  getParentRoute: () => ExploreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/explore': typeof ExploreRouteWithChildren
  '/trips': typeof TripsRoute
  '/blog/$id': typeof BlogIdRoute
  '/explore/coastal-karnataka': typeof ExploreCoastalKarnatakaRoute
  '/explore/heritage-trails': typeof ExploreHeritageTrailsRoute
  '/explore/hidden-villages': typeof ExploreHiddenVillagesRoute
  '/explore/western-ghats': typeof ExploreWesternGhatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/explore': typeof ExploreRouteWithChildren
  '/trips': typeof TripsRoute
  '/blog/$id': typeof BlogIdRoute
  '/explore/coastal-karnataka': typeof ExploreCoastalKarnatakaRoute
  '/explore/heritage-trails': typeof ExploreHeritageTrailsRoute
  '/explore/hidden-villages': typeof ExploreHiddenVillagesRoute
  '/explore/western-ghats': typeof ExploreWesternGhatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/explore': typeof ExploreRouteWithChildren
  '/trips': typeof TripsRoute
  '/blog/$id': typeof BlogIdRoute
  '/explore/coastal-karnataka': typeof ExploreCoastalKarnatakaRoute
  '/explore/heritage-trails': typeof ExploreHeritageTrailsRoute
  '/explore/hidden-villages': typeof ExploreHiddenVillagesRoute
  '/explore/western-ghats': typeof ExploreWesternGhatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/experiences'
    | '/explore'
    | '/trips'
    | '/blog/$id'
    | '/explore/coastal-karnataka'
    | '/explore/heritage-trails'
    | '/explore/hidden-villages'
    | '/explore/western-ghats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/experiences'
    | '/explore'
    | '/trips'
    | '/blog/$id'
    | '/explore/coastal-karnataka'
    | '/explore/heritage-trails'
    | '/explore/hidden-villages'
    | '/explore/western-ghats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/experiences'
    | '/explore'
    | '/trips'
    | '/blog/$id'
    | '/explore/coastal-karnataka'
    | '/explore/heritage-trails'
    | '/explore/hidden-villages'
    | '/explore/western-ghats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/explore/coastal-karnataka': {
      id: '/explore/coastal-karnataka'
      path: '/coastal-karnataka'
      fullPath: '/explore/coastal-karnataka'
      preLoaderRoute: typeof ExploreCoastalKarnatakaRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/heritage-trails': {
      id: '/explore/heritage-trails'
      path: '/heritage-trails'
      fullPath: '/explore/heritage-trails'
      preLoaderRoute: typeof ExploreHeritageTrailsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/hidden-villages': {
      id: '/explore/hidden-villages'
      path: '/hidden-villages'
      fullPath: '/explore/hidden-villages'
      preLoaderRoute: typeof ExploreHiddenVillagesRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/western-ghats': {
      id: '/explore/western-ghats'
      path: '/western-ghats'
      fullPath: '/explore/western-ghats'
      preLoaderRoute: typeof ExploreWesternGhatsRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ExploreRouteChildren {
  ExploreCoastalKarnatakaRoute: typeof ExploreCoastalKarnatakaRoute
  ExploreHeritageTrailsRoute: typeof ExploreHeritageTrailsRoute
  ExploreHiddenVillagesRoute: typeof ExploreHiddenVillagesRoute
  ExploreWesternGhatsRoute: typeof ExploreWesternGhatsRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCoastalKarnatakaRoute: ExploreCoastalKarnatakaRoute,
  ExploreHeritageTrailsRoute: ExploreHeritageTrailsRoute,
  ExploreHiddenVillagesRoute: ExploreHiddenVillagesRoute,
  ExploreWesternGhatsRoute: ExploreWesternGhatsRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRoute,
  ExploreRoute: ExploreRouteWithChildren,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
